### ISSUE TITLE
Add to DRF's Third Party Resources

### ISSUE THREAD

**Issue by jpadilla** [dealertrack/django-rest-framework-braces#6]
http://www.django-rest-framework.org/topics/third-party-resources/

**Comment by miki725** [comment]
duplicate of https://github.com/dealertrack/django-rest-framework-braces/issues/1

@jpadilla this was already added in https://github.com/tomchristie/django-rest-framework/pull/3118. I assumed its not showing up in the DRF docs since release was not made yet. Not sure what is the process there. Can you please advise?

**Comment by jpadilla** [comment]
@miki725 woops sorry about that. I'll take a look.

**Comment by miki725** [comment]
@jpadilla no worries at all.

its actually pretty cool that DRF maintainers opened first 3 tickets!!! and to top it all off, those tickets are to make 3rd party lib more visible!!!
